server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sys_user?allowMultiQueries=true&serverTimezone=GMT%2b8
  data:
    redis:
      database: 0
      host: 127.0.0.1
      timeout: 3000
      port: 6379
      password: 123456
      jedis:
        pool:
          max-active: 1000
          max-wait: 10
          min-idle: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/project-code/springboot/springboot-vue/springboot/files/
